name: Run tests 
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest selenium allure-pytest webdriver_manager
        pip install pytest selenium allure-pytest

    - name: Run tests
      run: |
        pytest --alluredir=allure-results
    - name: Generate Allure report
      run: |
        allure generate allure-results --clean
