name: Run tests 
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest --alluredir=allure-results
      continue-on-error: true

    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      with:
          name: allure-results
          path: allure-results
