name: Run tests 
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Allure
      run: |
        sudo apt-add-repository ppa:qameta/allure -y
        sudo apt-get update
        sudo apt-get install allure

    - name: Run tests
      run: pytest --alluredir=allure-results
      continue-on-error: true

    - name: List Allure results
      run: ls -la allure-results

    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report

    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      with:
          name: allure-report
          path: allure-report
